import {
  Briefcase,
  BarChart3,
  Target,
  Users,
  PieChart,
  Star,
  TrendingUp,
  FileText,
  Settings,
  Upload,
  Settings2,
  Activity,
  UserCheck,
  BookOpen,
  Crown,
  Building2,
  MapPin,
  MessageSquare,
  MessageCircle,
  Printer,
  FileCheck2,
  RotateCcw,
  Clock3,
} from "lucide-react";

export const navigationGroups = {
  gestao: {
    label: "PRESENÇA NO GOOGLE",
    icon: PieChart,
    items: [
      { id: "avaliacoes", label: "Avaliações", href: "/avaliacoes", icon: Star },
      { id: "estatisticas", label: "Estatísticas", href: "/estatisticas", icon: TrendingUp },
      { id: "relatorios", label: "Relatórios", href: "/relatorios", icon: FileText },
    ],
  },
  operacional: {
    label: "GESTÃO DE PRAZOS",
    icon: Briefcase,
    items: [
      {
        id: "espera",
        label: "Espera",
        href: "/espera",
        icon: Clock3,
        description: "Tempo de espera e atendimento",
      },
      {
        id: "recepcao",
        label: "Recepção",
        href: "/bi/produtividade",
        icon: Users,
        description: "5.192 Digital, 1.866 Presencial",
      },
      {
        id: "prazos",
        label: "Prazos",
        href: "/bi",
        icon: BarChart3,
        description: "15.591 títulos, 30,7% atraso",
      },
      {
        id: "tarefas",
        label: "Tarefas",
        href: "/bi/tarefas",
        icon: FileText,
        description: "Previsão de Carga Operacional",
      },
      {
        id: "metas",
        label: "Metas",
        href: "/bi/metas",
        icon: Target,
        description: "733 protocolos, gargalo 27,1d",
      },
      {
        id: "retornos",
        label: "Retornos",
        href: "/bi/retornos",
        icon: RotateCcw,
        description: "Consulte os retornos, responsáveis e observações de cada título.",
      },
      {
        id: "impressoes",
        label: "Impressões",
        href: "/controle-impressoes",
        icon: Printer,
        description: "Certidões e atos nos livros",
      },
      {
        id: "rastreio",
        label: "Rastreio",
        href: "/trajetoria-titulo",
        icon: MapPin,
        description: "Última localização e situação do protocolo",
      },
    ],
  },
  rhGestao: {
    label: "GESTÃO DE PESSOAS",
    icon: UserCheck,
    href: "/sistema/pessoas",
    items: [],
  },
  governancaIts: {
    label: "INSTRUÇÕES DE TRABALHO",
    icon: BookOpen,
    items: [
      {
        id: "gestao_its",
        label: "Gestão de ITs",
        href: "/administracao/its",
        icon: BookOpen,
        description: "Acompanhe, revise e aprove Instruções de Trabalho",
      },
    ],
  },
  // GRUPO TRABALHO: Operações do dia a dia do colaborador (Missão 4.3.6)
  trabalho: {
    label: "ROTINA DE TRABALHO",
    icon: Briefcase,
    items: [
      {
        id: "mensagens",
        label: "Mensagens",
        href: "/mensagens",
        icon: MessageSquare,
        description: "Comunicação corporativa em tempo real",
      },
      {
        id: "comunicados",
        label: "Comunicados",
        href: "/pessoas/comunicados",
        icon: FileText,
        description: "Mural interno e minhas ciências",
      },
      {
        id: "gestao_comunicados",
        label: "Gestão de Comunicados",
        href: "/sistema/pessoas?tab=comunicados",
        icon: FileCheck2,
        description: "Criar comunicados e gerenciar ciências",
      },
      {
        id: "minha_it",
        label: "Minha IT",
        href: "/minha-it",
        icon: BookOpen,
        description: "Instrução oficial • Responsável Técnico",
      },
    ],
  },
  // PESSOAL: apenas itens pessoais (Férias e Holerites)
  pessoas: {
    label: "MEU ESPAÇO",
    icon: Target,
    items: [
      {
        id: "ferias",
        label: "Férias",
        href: "/pessoas/ferias",
        icon: Briefcase,
        description: "Meu saldo e solicitações individuais",
      },
      {
        id: "holerites",
        label: "Holerites",
        href: "/pessoas/holerites",
        icon: FileText,
        description: "Meus contracheques e comprovantes",
      },
    ],
  },
  sistema: {
    label: "SISTEMA & TECNOLOGIA",
    icon: Settings,
    items: [
      {
        id: "central_operacoes",
        label: "Central de Operações",
        href: "/sistema/operacoes",
        icon: Activity,
        description: "Saúde e monitoramento",
      },
      {
        id: "importacao_contingencia",
        label: "Importação de Contingência",
        href: "/bi/importacoes",
        icon: Upload,
        description: "Carga manual de contingência",
      },
      { id: "configuracoes", label: "Configurações", href: "/configuracoes", icon: Settings2 },
      {
        id: "gestao_mensagens",
        label: "Gestão de Mensagens",
        href: "/administracao/mensagens",
        icon: MessageCircle,
        description: "Políticas, métricas e governança",
      },
    ],
  },
  master: {
    label: "MASTER SAAS",
    icon: Crown,
    items: [
      {
        id: "cartorios_tenants",
        label: "Cartórios (Tenants)",
        href: "/master/tenants",
        icon: Building2,
        description: "Gestão multi-tenant da plataforma",
      },
      {
        id: "mensagens_saas",
        label: "Mensagens SaaS",
        href: "/master/mensagens",
        icon: MessageSquare,
        description: "Telemetria e volume global de mensageria",
      },
    ],
  },
};
