import { ControleImpressoesData, ImpressaoItemRow } from '@/types/controle-impressoes';

export const MOCK_CONTROLE_IMPRESSOES: ControleImpressoesData = {
  ultimaSincronizacao: '02/09/2026 11:45',
  totalRegistros: 104,
  certidaoStats: {
    demanda: 85,
    produzidas: 92,
    pendencias: 47,
    saldoOperacional: -7,
    taxaAtendimento: 108,
    tempoMedio: 1.3,
    backlogInicio: 54,
    backlogFinal: 47,
  },
  livroStats: {
    demanda: 85,
    produzidas: 78,
    pendencias: 34,
    saldoOperacional: -11,
    taxaAtendimento: 92,
    tempoMedio: 0.8,
    backlogInicio: 45,
    backlogFinal: 34,
  },
  evolucaoDiaria: [
    { data: '20/08', demanda: 72, produzidasCertidao: 68, produzidasLivro: 60 },
    { data: '21/08', demanda: 88, produzidasCertidao: 82, produzidasLivro: 75 },
    { data: '22/08', demanda: 65, produzidasCertidao: 70, produzidasLivro: 58 },
    { data: '23/08', demanda: 80, produzidasCertidao: 75, produzidasLivro: 70 },
    { data: '24/08', demanda: 55, produzidasCertidao: 62, produzidasLivro: 54 },
    { data: '25/08', demanda: 86, produzidasCertidao: 90, produzidasLivro: 78 },
    { data: '26/08', demanda: 78, produzidasCertidao: 80, produzidasLivro: 72 },
    { data: '27/08', demanda: 48, produzidasCertidao: 55, produzidasLivro: 46 },
    { data: '28/08', demanda: 74, produzidasCertidao: 76, produzidasLivro: 68 },
    { data: '29/08', demanda: 68, produzidasCertidao: 72, produzidasLivro: 64 },
    { data: '30/08', demanda: 82, produzidasCertidao: 85, produzidasLivro: 76 },
    { data: '31/08', demanda: 58, produzidasCertidao: 64, produzidasLivro: 55 },
    { data: '01/09', demanda: 80, produzidasCertidao: 84, produzidasLivro: 74 },
    { data: '02/09', demanda: 66, produzidasCertidao: 70, produzidasLivro: 62 },
  ],
  distribuicaoNatureza: [
    { nome: 'PRENOTADO • Escritura', quantidade: 112, percentual: 28, cor: '#6366f1' },
    { nome: 'PRENOTADO • Instr. Particular', quantidade: 67, percentual: 16, cor: '#06b6d4' },
    { nome: 'INTIMAÇÃO • Intimação', quantidade: 31, percentual: 8, cor: '#3b82f6' },
    { nome: 'RETIFICAÇÃO DE ÁREA • Petição', quantidade: 18, percentual: 5, cor: '#8b5cf6' },
    { nome: 'HIS - Habitação de Interesse Social', quantidade: 14, percentual: 4, cor: '#ec4899' },
    { nome: 'HMP - Habitação de Mercado Popular', quantidade: 9, percentual: 2, cor: '#f59e0b' },
    { nome: 'Outros', quantidade: 43, percentual: 37, cor: '#64748b' },
  ],
  distribuicaoBacklog: [
    { faixa: '0 - 1 dia', quantidade: 24, percentual: 23, cor: '#10b981' },
    { faixa: '2 - 3 dias', quantidade: 22, percentual: 21, cor: '#06b6d4' },
    { faixa: '4 - 7 dias', quantidade: 18, percentual: 17, cor: '#f59e0b' },
    { faixa: '8 - 15 dias', quantidade: 16, percentual: 15, cor: '#f97316' },
    { faixa: '16 + dias', quantidade: 24, percentual: 24, cor: '#ef4444' },
  ],
  itens: [
    {
      id: 'row-1',
      protocolo: 640339,
      numeroLivro: '28903',
      tipoNatureza: 'PRENOTADO • Escritura',
      ultimoRegistro: '28/08/2026 15:54',
      certidaoStatus: 'REALIZADO',
      certidaoData: '28/08/2026 15:54',
      livroStatus: 'REALIZADO',
      livroData: '28/08/2026 15:55',
      diasPendente: 0,
      linkOnr: 'https://registradores.onr.org.br',
    },
    {
      id: 'row-2',
      protocolo: 640401,
      numeroLivro: '29012',
      tipoNatureza: 'INTIMAÇÃO • Intimação',
      ultimoRegistro: '29/08/2026 10:38',
      certidaoStatus: 'REALIZADO',
      certidaoData: '29/08/2026 11:02',
      livroStatus: 'PENDENTE',
      livroData: null,
      diasPendente: 2,
      linkOnr: 'https://registradores.onr.org.br',
    },
    {
      id: 'row-3',
      protocolo: 640455,
      numeroLivro: '29044',
      tipoNatureza: 'RETIFICAÇÃO DE ÁREA • Petição',
      ultimoRegistro: '30/08/2026 09:15',
      certidaoStatus: 'PENDENTE',
      certidaoData: null,
      livroStatus: 'PENDENTE',
      livroData: null,
      diasPendente: 3,
      linkOnr: 'https://registradores.onr.org.br',
    },
    {
      id: 'row-4',
      protocolo: 640512,
      numeroLivro: '29101',
      tipoNatureza: 'PRENOTADO • Instr. Particular',
      ultimoRegistro: '30/08/2026 14:22',
      certidaoStatus: 'NAO_APLICAVEL',
      certidaoData: null,
      livroStatus: 'REALIZADO',
      livroData: '30/08/2026 14:45',
      diasPendente: 0,
      linkOnr: 'https://registradores.onr.org.br',
    },
    {
      id: 'row-5',
      protocolo: 640520,
      numeroLivro: '29115',
      tipoNatureza: 'HIS - Hab. Interesse Social',
      ultimoRegistro: '31/08/2026 11:07',
      certidaoStatus: 'REALIZADO',
      certidaoData: '31/08/2026 11:25',
      livroStatus: 'REALIZADO',
      livroData: '31/08/2026 11:27',
      diasPendente: 0,
      linkOnr: 'https://registradores.onr.org.br',
    },
    {
      id: 'row-6',
      protocolo: 640588,
      numeroLivro: '29142',
      tipoNatureza: 'PRENOTADO • Escritura',
      ultimoRegistro: '31/08/2026 16:40',
      certidaoStatus: 'PENDENTE',
      certidaoData: null,
      livroStatus: 'REALIZADO',
      livroData: '31/08/2026 16:55',
      diasPendente: 1,
      linkOnr: 'https://registradores.onr.org.br',
    },
    {
      id: 'row-7',
      protocolo: 640612,
      numeroLivro: '29180',
      tipoNatureza: 'HMP - Hab. Mercado Popular',
      ultimoRegistro: '01/09/2026 08:30',
      certidaoStatus: 'REALIZADO',
      certidaoData: '01/09/2026 08:45',
      livroStatus: 'PENDENTE',
      livroData: null,
      diasPendente: 1,
      linkOnr: 'https://registradores.onr.org.br',
    },
    {
      id: 'row-8',
      protocolo: 640690,
      numeroLivro: '29210',
      tipoNatureza: 'PRENOTADO • Formal de Partilha',
      ultimoRegistro: '01/09/2026 14:15',
      certidaoStatus: 'PENDENTE',
      certidaoData: null,
      livroStatus: 'PENDENTE',
      livroData: null,
      diasPendente: 1,
      linkOnr: 'https://registradores.onr.org.br',
    },
    {
      id: 'row-9',
      protocolo: 640705,
      numeroLivro: '29235',
      tipoNatureza: 'PRENOTADO • Escritura',
      ultimoRegistro: '02/09/2026 09:10',
      certidaoStatus: 'REALIZADO',
      certidaoData: '02/09/2026 09:25',
      livroStatus: 'REALIZADO',
      livroData: '02/09/2026 09:30',
      diasPendente: 0,
      linkOnr: 'https://registradores.onr.org.br',
    },
    {
      id: 'row-10',
      protocolo: 640744,
      numeroLivro: '29280',
      tipoNatureza: 'RETIFICAÇÃO DE ÁREA • Petição',
      ultimoRegistro: '02/09/2026 10:45',
      certidaoStatus: 'PENDENTE',
      certidaoData: null,
      certidaoResponsavel: null,
      livroStatus: 'PENDENTE',
      livroData: null,
      livroResponsavel: null,
      diasPendente: 0,
      linkOnr: 'https://registradores.onr.org.br',
    },
  ],
  operadores: [
    { nome: 'Ana Paula', totalLivro: 45, totalCertidao: 38, total: 83 },
    { nome: 'Marcos Vinicius', totalLivro: 32, totalCertidao: 41, total: 73 },
    { nome: 'Juliana Ferreira', totalLivro: 28, totalCertidao: 22, total: 50 },
  ],
};

